// Success messages
export const successMessage = {
  REQ_REJECTED: 'Friend Request Rejected',
  REQ_ACCEPTED: 'Friend Request Accepted',
  USER_REGISTERED: 'User registered successfully',
  OTP_SEND_SUCCESS: 'Otp Send successfully',
  QUERY_SEND_SUCCESS: 'Thank You for Reaching Out!',
  RESET_PASSWORD_LINK_SENT: 'Password Reset Link Send successfully',
  RESET_PASSWORD_SUCCESS: 'Password Reset  successfully',
  VEHICLE_ADDED: 'Vehicle added successfully!',
  DOCUMENT_UPLOAD: 'Document Upload successfully',
  DOCUMENT_UPDATE: 'Document Update successfully',
  VEHICLE_UPDATED: 'Vehicle updated successfully!',
  VEHICLE_DELETED: 'Vehicle deleted successfully!',
  BANKDETAIL_UPDATED: 'Bank detail updated successfully!',
  OTP_SEND: 'Otp Send successfully',
  NOTIFICATION_SENT: 'notification sent successfully',
  PAYMENT_SUCCESS: 'Payment success!',
  COUPON_APPLIED: 'Coupon Applied Successfully!',
  COUPON_REMOVED: 'Coupon Removed Successfully!',
  DRIVER_ASSIGNED: 'Driver Assign Successfully!',
  SENT: (resource: string) => `${resource} sent successfully`,
  COMPLETED: (resource: string) => `${resource} successfully`,
  UPDATED: (resource: string) => `${resource} updated successfully`,
  DELETED: (resource: string) => `${resource} deleted successfully`,
  FETCH: (resource: string) => `${resource}  fetched successfully`,
  ALL_FETCH: (resource: string) => `All ${resource}  fetched successfully`,
  FOUND: (resource: string) => `${resource}  found successfully`,
  SAVED: (resource: string) => `${resource} Information Saved Successfully!`,
  LIKE: (resource: string) => `${resource} Liked successfully`,
  UNLIKE: (resource: string) => `${resource} UnLiked successfully`,
  COMMENT: (resource: string) => `${resource} successfully`,
  REGISTER: (resource: string) => `${resource} registered successfully`,
  LOGIN: (resource: string) => `${resource} login successfully`,
  LOGOUT: (resource: string) => `${resource} logout successfully`,
  ORDER: (resource: string) => `Order ${resource} successfully`
};

// Error messages
export const errorMessage = {
  INTERNAL_SERVER_ERROR: 'Internal server error',
  USER_EXISTS: 'User already exists',
  INVALID_CREDENTIALS: 'Invalid credentials',
  SOMETHING_WENT_WRONG: 'something went wrong ',
  USER_REGISTER_ERROR: 'Error registering user',
  USER_LOGIN_ERROR: 'Error during login',
  LOGOUT_ERROR: 'Error during logout',
  MISSING_TOKEN: 'Unauthorized: Missing token',
  INVALID_TOKEN: 'Unauthorized: Invalid token',
  UNAUTHORIZED_ACCESS: 'unauthorized to access',
  USER_NOT_FOUND: 'User does not found',
  EMAIL_NOT_EXIST: 'Email does not exist',
  WRONG_PASSWORD: 'Wrong Password',
  OLD_NEW_PASSWORD_NOT_EQUAL: 'Old passwod and new password can not be same!',
  INVALID_OTP: 'Unauthorized: Invalid otp',
  OTP_SEND_FAILD: 'Faild To Send otp',
  USER_EXIST_SAME_CONTACT: 'User with same contact exist',
  USER_UPDATE_FAILD: 'Faild To Update User Information! ',
  ROLE_EXISTS: 'Role already exists',
  ROLE_NOT_FOUND: 'Role Not Found',
  PERMISSION_NOT_FOUND: 'Permission Not Found',
  PERMISSION_EXISTS: 'Permission already exists',
  CITY_DATA_EXIST: 'City with same country exist',
  DATA_NOT_FOUND: 'Data not found. ',
  MISSING_IDS: 'One or more required IDs are missing.',
  ROLE_EXIST: 'Role already exist',
  EXPIRED: 'Coupon  expired',
  MAX_USAGE_REACHED: 'Coupon max usage reached',
  ORDER_ACCEPTED: 'Already a order accepted',
  NOT_FOUND: (resource: string) => `${resource} not found`,
  FAILD: (resource: string) => `${resource} Faild`,
  EXIST: (resource: string) => `${resource} already sent`,
  NOT_EXIST: (resource: string) => `${resource} not  exist`,
  ERROR: (resource: string) => ` Error during ${resource} `,
  INVALID: (resource: string) => ` Invalid ${resource} `,
  ORDER_ASSGINED: 'Order already has been assigned'
};
